/**
 * THE FIRST CARD, BEFORE ANYTHING IS DOWNLOADED.
 *
 *   npx tsx scripts/build-starter.ts     writes src/lib/data/starter-pack.ts
 *
 * Opening this site means: fetch 13.8 MB, decode it, build a rarity index,
 * hand it to a worker, rank a batch — and only then does a card appear. On a
 * slow connection that is 75.8 seconds of nothing.
 *
 * There is already a fallback (`SAMPLE_TITLES`) so the deck is never empty,
 * but it deliberately carries no poster paths: it predates the TMDB catalog
 * and renders as generated art. So the first thing a new visitor sees is not
 * the product — it is the placeholder for the product.
 *
 * This bakes a small, real pack into the JavaScript bundle. No fetch, no
 * decode, no ranking: the cards are there when the page is. The full catalog
 * arrives behind it and takes over.
 *
 * WHY THESE TITLES. The most-voted works in the catalog, spread deliberately:
 * a cap per language and per genre, and a guaranteed share of series. The
 * opening hand is the only thing a person judges the product on before they
 * have taught it anything, and twenty English action films would say this is a
 * Hollywood app to exactly the audience the catalog was rebuilt for.
 */
import { writeFileSync } from "node:fs";
import { loadFullCatalog } from "./lib/catalog";
import type { Title } from "../src/lib/types";

const COUNT = Number(process.env.COUNT ?? 24);
const MAX_PER_LANG = Number(process.env.MAX_PER_LANG ?? 3);
const MAX_PER_GENRE = Number(process.env.MAX_PER_GENRE ?? 4);
const TV_SHARE = Number(process.env.TV_SHARE ?? 0.3);

const catalog = loadFullCatalog().filter((t) => t.posterPath);
const byVotes = [...catalog].sort((a, b) => b.voteCount - a.voteCount);

function pick(want: number, wantTv: boolean, taken: Set<string>): Title[] {
  const langs = new Map<string, number>();
  const genres = new Map<string, number>();
  const out: Title[] = [];
  for (const t of byVotes) {
    if (out.length >= want) break;
    if (taken.has(t.id)) continue;
    if ((t.type === "tv") !== wantTv) continue;
    const l = langs.get(t.originalLanguage) ?? 0;
    if (l >= MAX_PER_LANG) continue;
    const g = t.genres[0] ?? "—";
    if ((genres.get(g) ?? 0) >= MAX_PER_GENRE) continue;
    langs.set(t.originalLanguage, l + 1);
    genres.set(g, (genres.get(g) ?? 0) + 1);
    taken.add(t.id);
    out.push(t);
  }
  return out;
}

const taken = new Set<string>();
const tvWant = Math.round(COUNT * TV_SHARE);
const chosen = [...pick(COUNT - tvWant, false, taken), ...pick(tvWant, true, taken)];

/* interleaved, so the opening hand alternates rather than showing every film
   and then every series — the second card should already look different */
const films = chosen.filter((t) => t.type === "movie");
const series = chosen.filter((t) => t.type === "tv");
const order: Title[] = [];
for (let i = 0; i < Math.max(films.length, series.length); i++) {
  if (films[i]) order.push(films[i]);
  if (i % 2 === 1 && series[Math.floor(i / 2)]) order.push(series[Math.floor(i / 2)]);
}
for (const s of series) if (!order.includes(s)) order.push(s);

/**
 * Trimmed hard. This is in the JavaScript bundle, on the critical path, for
 * every visitor — so it carries what a CARD draws and nothing else. No
 * synopsis, no keywords, no cast, no co-watch links: the full catalog supplies
 * all of that seconds later, and ranking never runs against this pack.
 */
const slim = order.map((t) => ({
  id: t.id,
  type: t.type,
  title: { en: t.title.en, ar: t.title.ar, ...(t.title.original ? { original: t.title.original } : {}) },
  overview: { en: "", ar: "" },
  year: t.year,
  genres: t.genres.slice(0, 2),
  keywords: [],
  people: { director: "", cast: [] },
  originalLanguage: t.originalLanguage,
  rating: t.rating,
  voteCount: t.voteCount,
  popularity: t.popularity,
  posterPath: t.posterPath,
}));

const bytes = JSON.stringify(slim).length;

writeFileSync(
  "src/lib/data/starter-pack.ts",
  `import type { Title } from "../types";

/**
 * GENERATED by \`npm run starter\` — do not edit.
 *
 * ${slim.length} real titles, ${(bytes / 1024).toFixed(1)} KB, bundled into the JavaScript so the first
 * card renders before \`catalog.json\` has been asked for. See
 * \`scripts/build-starter.ts\` for why these titles and why this shape.
 *
 * Trimmed to what a card draws: no synopsis, no keywords, no cast, no
 * co-watch links. The real catalog supplies those seconds later and the
 * ranking never runs against this pack.
 */
export const STARTER_PACK: Title[] = ${JSON.stringify(slim, null, 2)} as unknown as Title[];
`
);

const langCount = new Set(slim.map((t) => t.originalLanguage)).size;
console.log(
  `src/lib/data/starter-pack.ts — ${slim.length} titles, ${(bytes / 1024).toFixed(1)} KB\n` +
    `  ${slim.filter((t) => t.type === "movie").length} films / ${slim.filter((t) => t.type === "tv").length} series · ${langCount} languages\n` +
    `  ${slim.slice(0, 6).map((t) => t.title.en).join(" · ")}`
);
